FROM rasa/rasa:latest

EXPOSE 5005

WORKDIR /app

USER root

RUN pip3 install rasa[spacy]

RUN python -m spacy download fr_core_news_lg

COPY ./ ./

ENTRYPOINT [ "" ]

RUN rasa train

USER 1001

CMD [ "rasa", "run", "-m", "models", "--enable-api", "--cors", "*", "--debug" ]